== KPI-2-0: Station characteristics

=== Status

Draft

=== Rules for implementation

.Completeness of station characteristics implementation rules
|===
|ID |Element |Rules |Individual rating |Maximum score 

.2+|2-0-00
.2+|Coordinates
`wmdr:geospatialLocation`
|A geopositioning method is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/geospatialLocation/GeospatialLocation/geopositioningMethod`|1 .2+|2 (for each added location) 
|The begin position of valid period is specified. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/geospatialLocation/GeospatialLocation/validPeriod/TimePeriod/beginPosition` |1


|2-0-01
|WMO region
`wmdr:wmoRegion`
|A WMO region (code list: http://codes.wmo.int/wmdr/WMORegion) is specified and it matches the coordinates.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/wmoRegion`
|1 |1


.2+|2-0-02
.2+|Time zone
`wmdr:timeZone`
|A time zone is specified and it matches the coordinates. |1 .2+|2 
|The begin position of valid period is specified.|1 


.2+|2-0-03
.2+|Supervising organization
`wmdr:responsibleParty`
|A supervising organization is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/responsibleParty/ResponsibleParty/responsibleParty/CI_ResponsibleParty/organisationName/CharacterString`
|1 .2+|2 
|The begin position of valid period is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/responsibleParty/ResponsibleParty/validPeriod/TimePeriod/beginPosition`|1


|2-0-04
|Station URL
|URL is provided and valid.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/onlineResource/CI_OnlineResource/linkage/URL`
|1 |1


|2-0-05
|Other link (URL)
|At least one other link is provided and all URLs are valid.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/onlineResource/CI_OnlineResource/linkage/URL` 
|1 |1


.2+|2-0-06
.2+|Site description
`wmdr:description`
|Site description is provided. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/description/Description/description`|1 .2+|2 
|Requirement for minumum length is fulfilled. |1


.2+|2-0-07
.2+|Climate zone
`wmdr:climateZone`
|A climate zone (code list: http://codes.wmo.int/wmdr/ClimateZone) is specified. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/climateZone/ClimateZone/climateZone`|1 .2+|2 
|The begin position of valid period is specified. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/climateZone/ClimateZone/validPeriod/TimePeriod/beginPosition`|1


.2+|2-0-08
.2+|Predominant surface cover
`wmdr:surfaceCover`
|A surface cover classification scheme (code list: http://codes.wmo.int/wmdr/SurfaceCoverClassification) and the surface cover (code lists: http://codes.wmo.int/wmdr/SurfaceCoverXXXX) are specifed and not "unknown". 

XPaths: `/WIGOSMetadataRecord/facility/ObservingFacility/surfaceCover/SurfaceCover/surfaceCoverClassification`, `/WIGOSMetadataRecord/facility/ObservingFacility/surfaceCover/SurfaceCover/surfaceCover`
|1 .2+|2 
|The begin position of valid period is specified. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/surfaceCover/SurfaceCover/validPeriod/TimePeriod/beginPosition`
|1


.2+|2-0-09
.2+|Surface roughness
`wmdr:surfaceRoughness`
|The Surface roughness (code list: http://codes.wmo.int/wmdr/SurfaceRoughnessDavenport) is specified and not "unknown". |1 .2+|2 
|The begin position of valid period is specified. |1


.5+|2-0-10
.5+|Topography or bathymetry
`wmdr:topographyBathymetry`
|The local topography (based on Speight 2009) (code list: http://codes.wmo.int/wmdr/LocalTopography ) is specified and  not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/topographyBathymetry/TopographyBathymetry/localTopography`|1 .5+|5  
|The relative elevation is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/topographyBathymetry/TopographyBathymetry/relativeElevation`|1
|The Topographic context (based on Hammond 1954) (code list: http://codes.wmo.int/wmdr/TopographicContext ) is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/topographyBathymetry/TopographyBathymetry/topographicContext`|1
|Altitude/depth (code list: http://codes.wmo.int/wmdr/AltitudeOrDepth) is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/topographyBathymetry/TopographyBathymetry/altitudeOrDepth`|1
|The begin position of valid period is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/topographyBathymetry/TopographyBathymetry/validPeriod/TimePeriod/beginPosition`|1


.3+|2-0-11
.3+|Population
`wmdr:population`
|Values for population in 10 km range is added. |1 .3+|3  
|Values for population in 50 km range is added. |1
|The begin position of valid period is specified. |1


.5+|2-0-12
.5+|Station / platform event logbook
`wmdr:facilityLog`
|A date is added (range or single day). 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/facilityLog/FacilityLog/logEntry/EventReport/validPeriod/TimePeriod/beginPosition`
|1 .5+|5 (for each event)  
|The event is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/facilityLog/FacilityLog/logEntry/EventReport/typeOfEvent`|1
|A description is provided.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/facilityLog/FacilityLog/logEntry/EventReport/description`|1
|The author is named.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/facilityLog/FacilityLog/logEntry/EventReport/author`|1
|The event has an online reference.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/facilityLog/FacilityLog/logEntry/EventReport/documentationURL`|1


.2+|2-0-13
.2+|Territory/Country
`wmdr:territory`
|A territory or country is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/territory/Territory/territoryName`|1 .2+|2 
|The begin position of valid period is specified. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/territory/Territory/validPeriod/TimePeriod/beginPosition`|1

|==
=== Guidance to score well on this assessment

_Recommendations and hints/advice._

