== KPI-3-3: 	Data generation

=== Status

Draft

=== Rules for implementation

.Data generation implementation rules
|===
|ID |Section |Element |Rules |Individual score |Maximum score

|3-3-00
|Sampling
|Sampling strategy `wmdr:samplingStrategy`
|Sampling strategy (code list: http://codes.wmo.int/wmdr/SamplingStrategy) is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/sampling/Sampling/samplingStrategy`
|1
|1


|3-3-01
|
|Sampling interval `wmdr:temporalSamplingInterval`	
|Sampling interval is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/sampling/Sampling/temporalSamplingInterval`
|1
|1


|3-3-02
|
|Sampling period `wmdr:samplingTimePeriod`
|Sampling period is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/sampling/Sampling/samplingTimePeriod`
|1
|1


|3-3-03
|
|Spatial sampling resolution `wmdr:spatialSamplingResolution`
|Sampling resolution is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/sampling/Sampling/spatialSamplingResolution`
|1
|1


.2+|3-3-04
.2+|
.2+|Sampling procedure `wmdr:samplingProcedure`
|Sampling procedure is specified and not "unknown". 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/sampling/Sampling/samplingProcedure`|1 .2+|2 
|Sampling procedure description is provided.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/sampling/Sampling/samplingProcedureDescription`|1


|3-3-05
|
|Sample treatment	`wmdr:sampleTreatment`
|Sample treatment is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/sampling/Sampling/sampleTreatment`
|1
|1


|3-3-06
|Processing
|Aggregation period `wmdr:aggregationPeriod`
|Aggregation period is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/processing/Processing/aggregationPeriod`
|1
|1


|3-3-07
|
|Data processing method `wmdr:dataProcessing`
|Data processing method is described. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/processing/Processing/dataProcessing`
|1
|1


|3-3-08
|
|Software/processor and version `wmdr:dataProcessing`
|Name and version of the software or processor are specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/processing/Processing/softwareDetails`
|1
|1


|3-3-09
|
|Software/source code repository URL `wmdr:softwareURL`
|URL is provided and valid.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/processing/Processing/softwareURL`
|1
|1


|3-3-10
|
|Processing/analysis centre `wmdr:processingCentre`
|Processing/analysis centre is named and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/processing/Processing/processingCentre`
|1
|1


|3-3-11
|Reporting
|Diurnal base time `wmdr:diurnalBaseTime`
|Diurnal base time is specified.
|1
|1


|3-3-12
|
|Number of observations in reporting period `wmdr:numberOfObservationsInReportingInterval`
|Number of observations in reporting period is specified. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/numberOfObservationsInReportingInterval`
|1
|1


|3-3-13
|
|Measurement unit	`wmdr:uom`
|	Unit (code list: http://codes.wmo.int/wmdr/unit) is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/uom`
|1
|1


|3-3-14
|
|Data policy `wmdr:dataPolicy`
|Data policy (code list: http://codes.wmo.int/wmdr/DataPolicy) is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/dataPolicy/DataPolicy/dataPolicy`
|1
|1


|3-3-15
|
|Spatial reporting interval `wmdr:spatialReportingInterval`
|Spatial reporting interval is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/spatialReportingInterval`
|1
|1


|3-3-16
|
|Timeliness (Latency of reporting) `wmdr:timeliness`
|Time lag is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/timeliness`
|1
|1


|3-3-17
|
|Numerical resolution `wmdr:numericalResolution`
|Numerical resolution is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/numericalResolution`
|1
|1


|3-3-18
|
|Level of data `wmdr:levelOfData`
|Level of data (code list: http://codes.wmo.int/wmdr/LevelOfData) is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/levelOfData`
|1
|1


|3-3-19
|
|Data format `wmdr:dataFormat`
|Data format (code list: http://codes.wmo.int/wmdr/DataFormat) is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/dataFormat`
|1
|1


|3-3-20
|
|Data format version `wmdr:dataFormatVersion`
|Data format version is specified.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/dataFormatVersion`
|1
|1


|3-3-21
|
|Reference datum `wmdr:referenceDatum`
|Reference datum is described.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/referenceDatum/VerticalDatum/remarks`
|1
|1


|3-3-22
|
|Reference time source `wmdr:referenceTimeSource`
|Reference time source (code list: http://codes.wmo.int/wmdr/ReferenceTime) is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/referenceTimeSource`
|1
|1


|3-3-26
|
|Meaning of timestamp in data reports `wmdr:timeStampMeaning`
|Meaning of timestamp (code list:  http://codes.wmo.int/wmdr/TimeStampMeaning) in data reports is specified and not "unknown".

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/timeStampMeaning`
|1
|1


.4+|3-3-27
.4+|
.4+|Attribution `wmdr:attribution`
|Title of work is specified. 

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/dataPolicy/DataPolicy/attribution/Attribution/title`|1 .4+|4 
|Attribution URL is given and valid.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/dataPolicy/DataPolicy/attribution/Attribution/originatorURL/CI_OnlineResource/linkage/URL`|1
|Originator of work is named.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/dataPolicy/DataPolicy/attribution/Attribution/originator/CI_ResponsibleParty/organisationName/CharacterString`|1
|Source work basis (URL) is added and valid.

XPath: `/WIGOSMetadataRecord/facility/ObservingFacility/observation/ObservingCapability/observation/OM_Observation/procedure/Process/deployment/Deployment/dataGeneration/DataGeneration/reporting/Reporting/dataPolicy/DataPolicy/attribution/Attribution/source/CI_OnlineResource/linkage/URL`|1

|===

=== Guidance to score well on this assessment

_Recommendations and hints/advice._
